-- =============================================
-- Categories Table Setup for EnFans
-- =============================================

-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    sort_order INTEGER DEFAULT 0
);

-- Insert default categories (ON CONFLICT handles duplicate runs)
INSERT INTO categories (name, sort_order) VALUES
    ('Albums', 1),
    ('Fashion', 2),
    ('Decor', 3)
ON CONFLICT (name) DO NOTHING;

-- Enable Row Level Security
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY IF NOT EXISTS "Allow public read access on categories"
    ON categories
    FOR SELECT
    TO public
    USING (true);

-- Verify the setup
SELECT * FROM categories ORDER BY sort_order;
