-- =============================================
-- Database Refactor: Foreign Key Relationships
-- =============================================

-- 1. Create categories table (if not exists)
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    sort_order INTEGER DEFAULT 0
);

-- 2. Insert default categories
INSERT INTO categories (name, sort_order) VALUES
    ('Albums', 1),
    ('Fashion', 2),
    ('Decor', 3)
ON CONFLICT (name) DO NOTHING;

-- 3. Add category_id column to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS category_id BIGINT;

-- 4. Add Foreign Key constraint
ALTER TABLE products
ADD CONSTRAINT fk_products_category
FOREIGN KEY (category_id) REFERENCES categories(id)
ON DELETE SET NULL;

-- 5. Migrate existing category data (if any text categories exist)
UPDATE products p
SET category_id = c.id
FROM categories c
WHERE p.category = c.name AND p.category_id IS NULL;

-- 6. Enable RLS on categories table
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- 7. Create policy for public read access on categories
DROP POLICY IF EXISTS "Allow public read access on categories" ON categories;
CREATE POLICY "Allow public read access on categories"
    ON categories
    FOR SELECT
    TO public
    USING (true);

-- Verify setup
SELECT p.id, p.title, p.category_id, c.name as category_name 
FROM products p 
LEFT JOIN categories c ON p.category_id = c.id;
